input:
  examples:
   - examples.txt
    # - expressions-1.json
  keywords:
  - keywords.yml
  providers:
  - botshot_nlu.provider.RestProvider:
    - "http://zilinec.me/foo.json"
  - botshot_nlu.provider.RestProvider:
      "api_url": "http://zilinec.me/foo.json"

keywords_from_examples: true

intent:
  model: botshot_nlu.intent.neural_net_model.NeuralNetModel
  pipeline:
  - botshot_nlu.tokenizer.whitespace.WhitespaceTokenizer
  - botshot_nlu.pipeline.featurizer.BagOfWords

entities:

  course:
    keywords:
      model: botshot_nlu.keywords.trie.TrieKeywordExtractor
  fruit:
    keywords:
      model: botshot_nlu.keywords.embedding.EmbeddingKeywordExtractor
      embedding_file: /home/goovi/datasets/fasttext-en/cc.en.300.vec
  color:
    keywords:
      model: botshot_nlu.keywords.embedding.EmbeddingKeywordExtractor
      embedding_file: /home/goovi/datasets/fasttext-en/cc.en.300.vec
  place:
    keywords:
      model: botshot_nlu.keywords.embedding.EmbeddingKeywordExtractor
      embedding_file: /home/goovi/datasets/fasttext-en/cc.en.300.vec
  transport_type:
      keywords:
        model: botshot_nlu.keywords.trie.TrieKeywordExtractor
